NotebookZeta/Models/ErrorViewModel.cs
namespace NotebookZeta.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

NotebookZeta/Models/IndexViewModel.cs
using System.Collections.Generic;
using NotebookZeta.Core;

namespace NotebookZeta.Models
{
	public class IndexViewModel
	{
		public IEnumerable<Note> NotesList { get; set; }
	}
}

NotebookZeta/Models/NoteDto.cs
using Microsoft.AspNetCore.Http;

namespace NotebookZeta.Models
{
    public class NoteDto
	{
		public int Id { get; set; }
		public string Title { get; set; }
		public string Text { get; set; }
		public IFormFileCollection Attachments { get; set; }
	}
}

NotebookZeta/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NotebookZeta.Models;
using System.Diagnostics;
using NotebookZeta.DataAccess;

namespace NotebookZeta.Controllers
{
	[Route("[controller]/[action]")]
	public class HomeController : Controller
	{
        private readonly UnitOfWork unitOfWork;

		public HomeController(UnitOfWork unitOfWork)
		{
			this.unitOfWork = unitOfWork;
		}

		[HttpGet]
		public IActionResult Index()
		{
            var notes = unitOfWork.GetAllNotes();
			return View(new IndexViewModel { NotesList = notes });
		}

		[HttpGet]
		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

NotebookZeta/Controllers/NotesController.cs
using Microsoft.AspNetCore.Mvc;
using NotebookZeta.Models;
using NotebookZeta.DataAccess;
using NotebookZeta.Core;
using System;
using System.Linq;
using System.Collections.Generic;

namespace NotebookZeta.Controllers
{
	[Route("[controller]/[action]")]
	public class NotesController : Controller
	{
        private readonly UnitOfWork unitOfWork;

		public NotesController(UnitOfWork unitOfWork)
		{
            this.unitOfWork = unitOfWork;
		}

		[HttpGet]
		[Route("{id}")]
		public IActionResult Get(int id)
		{
			var note = unitOfWork.GetNote(id);
			if (note == null)
				return NotFound();

			return View(note);
		}
		
		[HttpGet]
		[Route("{id}")]
		public IActionResult GetAttachment(int id)
		{
			var file = unitOfWork.GetAttachment(id);
			if (file == null)
				return NotFound();

			return File(file.Content, file.ContentType, file.FileName);
		}

		[HttpPost]
		public IActionResult Add(NoteDto noteDto)
		{
            var note = new Note
            {
                Title = noteDto.Title,
                Text = CastHelper.CastText(noteDto.Text),
                CreationTime = DateTime.Now
            };
            note.Attachments = noteDto.Attachments?
                .Select(file => CastHelper.CastFormFile(file, note))
                .ToList() ?? new List<AttachedFile>();
            
            unitOfWork.AddNote(note);
			return RedirectToAction("Index", "Home");
		}

		[HttpPost]
		[Route("{id}")]
		public IActionResult Remove(int id)
		{
			unitOfWork.RemoveNote(id);
			return RedirectToAction("Index", "Home");
		}
	}
}

NotebookZeta/Views/Home/Index.cshtml
@model IndexViewModel
@{
   ViewBag.Title = "Home page";
}

<h3>Notes</h3>
<p>
	<ul>
		@foreach (var note in Model.NotesList)
		{
			<li>
				<a asp-area="" asp-controller="Notes" asp-action="Get" asp-route-id="@note.Id">@note.Title</a>
			</li>
		}
	</ul>
</p>

<hr />

<p>
	<form enctype="multipart/form-data" method="post" asp-area="" asp-controller="Notes" asp-action="Add">
		<p><input type="text" name="title" value="Title"></p>
		<p><textarea name="text">Text</textarea></p>
		<p><input type="file" name="attachments" multiple></p>
		<p><input type="submit" value="Add note"></p>
	</form>
</p>

NotebookZeta/Views/Notes/Get.cshtml
@model Note
@{
   ViewBag.Title = Model.Title;
}

<p>
	<h1>@Model.Title</h1>
	<h4>@Model.CreationTime</h4>
	@foreach (var line in Model.Text)
	{
		@line<br />
	}
</p>

<hr />

<h3>Attachments</h3>
<p>
	<ol>
		@foreach (var file in Model.Attachments)
		{
			<li>
				<a asp-area="" asp-controller="Notes" asp-action="GetAttachment" asp-route-id="@file.Id">
					@file.FileName</a>
			</li>
		}
	</ol>
</p>

<p>
	<form method="post" asp-area="" asp-controller="Notes" asp-action="Remove" asp-route-id="@Model.Id">
		<input type="submit" value="Delete note">
	</form>
</p>

NotebookZeta/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - NotebookZeta</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">NotebookZeta</a>
            </div>
            @*<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
					<li><a asp-area="" asp-controller="Home" asp-action="Error">Error</a></li>
				</ul>
            </div>*@
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - NotebookZeta</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>